const animalTheme = {
    name: '动物主题',
    emojiData: [
        { emoji: '🐼', word: 'panda', translation: '熊猫' },
        { emoji: '🐱', word: 'cat', translation: '猫' },
        { emoji: '🐶', word: 'dog', translation: '狗' },
        { emoji: '🐰', word: 'rabbit', translation: '兔子' },
        { emoji: '🦊', word: 'fox', translation: '狐狸' },
        { emoji: '🐨', word: 'koala', translation: '考拉' },
        { emoji: '🦁', word: 'lion', translation: '狮子' },
        { emoji: '🐯', word: 'tiger', translation: '老虎' },
        { emoji: '🐮', word: 'cow', translation: '奶牛' },
        { emoji: '🐷', word: 'pig', translation: '猪' },
        { emoji: '🐸', word: 'frog', translation: '青蛙' },
        { emoji: '🦒', word: 'giraffe', translation: '长颈鹿' },
        { emoji: '🦘', word: 'kangaroo', translation: '袋鼠' },
        { emoji: '🦔', word: 'hedgehog', translation: '刺猬' },
        { emoji: '🦡', word: 'badger', translation: '獾' },
        { emoji: '🦨', word: 'skunk', translation: '臭鼬' },
        { emoji: '🦦', word: 'otter', translation: '水獭' },
        { emoji: '🦥', word: 'sloth', translation: '树懒' },
        { emoji: '🦫', word: 'beaver', translation: '海狸' },
        { emoji: '🦃', word: 'turkey', translation: '火鸡' },
        { emoji: '🦆', word: 'duck', translation: '鸭子' },
        { emoji: '🦅', word: 'eagle', translation: '鹰' },
        { emoji: '🦉', word: 'owl', translation: '猫头鹰' },
        { emoji: '🦚', word: 'peacock', translation: '孔雀' },
        { emoji: '🦜', word: 'parrot', translation: '鹦鹉' },
        { emoji: '🦢', word: 'swan', translation: '天鹅' },
        { emoji: '🦩', word: 'flamingo', translation: '火烈鸟' },
        { emoji: '🐧', word: 'penguin', translation: '企鹅' },
        { emoji: '🦈', word: 'shark', translation: '鲨鱼' },
        { emoji: '🐋', word: 'whale', translation: '鲸鱼' },
        { emoji: '🐬', word: 'dolphin', translation: '海豚' },
        { emoji: '🦭', word: 'seal', translation: '海豹' },
        { emoji: '🐢', word: 'turtle', translation: '乌龟' },
        { emoji: '🦎', word: 'lizard', translation: '蜥蜴' },
        { emoji: '🐍', word: 'snake', translation: '蛇' },
        { emoji: '🐊', word: 'crocodile', translation: '鳄鱼' },
        { emoji: '🦕', word: 'dinosaur', translation: '恐龙' },
        { emoji: '🦖', word: 't-rex', translation: '霸王龙' },
        { emoji: '🦗', word: 'cricket', translation: '蟋蟀' },
        { emoji: '🪲', word: 'beetle', translation: '甲虫' },
        { emoji: '🦋', word: 'butterfly', translation: '蝴蝶' },
        { emoji: '🐛', word: 'caterpillar', translation: '毛毛虫' },
        { emoji: '🐌', word: 'snail', translation: '蜗牛' },
        { emoji: '🦂', word: 'scorpion', translation: '蝎子' },
        { emoji: '🕷️', word: 'spider', translation: '蜘蛛' },
        { emoji: '🦞', word: 'lobster', translation: '龙虾' },
        { emoji: '🦀', word: 'crab', translation: '螃蟹' },
        { emoji: '🐙', word: 'octopus', translation: '章鱼' },
        { emoji: '🦑', word: 'squid', translation: '鱿鱼' },
        { emoji: '🦐', word: 'shrimp', translation: '虾' },
        { emoji: '🐠', word: 'fish', translation: '热带鱼' }
    ],
    colors: {
        background: '#F3E5F5',
        text: '#4A148C',
        score: '#AB47BC'
    },
    sounds: {
        match: 'animal-match.mp3',
        levelUp: 'animal-levelup.mp3',
        background: 'animal-bg.mp3'
    },
    scoreMultiplier: 1.3,
    particleEffects: {
        color: '#E1BEE7',
        size: 6,
        speed: 2.8
    }
};

export default animalTheme;