const emotionTheme = {
    name: '情绪主题',
    emojiData: [
        { emoji: '😊', word: 'happy', translation: '开心' },
        { emoji: '😄', word: 'laugh', translation: '大笑' },
        { emoji: '🥰', word: 'love', translation: '喜爱' },
        { emoji: '😎', word: 'cool', translation: '酷' },
        { emoji: '🤗', word: 'hug', translation: '拥抱' },
        { emoji: '🤔', word: 'think', translation: '思考' },
        { emoji: '😮', word: 'surprised', translation: '惊讶' },
        { emoji: '😴', word: 'sleepy', translation: '困倦' },
        { emoji: '😋', word: 'yummy', translation: '美味' },
        { emoji: '🤩', word: 'excited', translation: '兴奋' },
        { emoji: '😌', word: 'relieved', translation: '放松' },
        { emoji: '🥳', word: 'party', translation: '派对' },
        { emoji: '😇', word: 'innocent', translation: '天真' },
        { emoji: '🤭', word: 'giggle', translation: '窃笑' },
        { emoji: '😉', word: 'wink', translation: '眨眼' },
        { emoji: '🤪', word: 'silly', translation: '搞怪' },
        { emoji: '😍', word: 'adore', translation: '崇拜' },
        { emoji: '🥺', word: 'plead', translation: '恳求' },
        { emoji: '😲', word: 'astonished', translation: '震惊' },
        { emoji: '🤯', word: 'mindblown', translation: '震撼' },
        { emoji: '😀', word: 'grin', translation: '咧嘴笑' },
        { emoji: '😃', word: 'smile', translation: '微笑' },
        { emoji: '😅', word: 'sweat smile', translation: '尴尬笑' },
        { emoji: '😂', word: 'joy', translation: '开怀大笑' },
        { emoji: '🥲', word: 'grateful', translation: '感激' },
        { emoji: '☺️', word: 'content', translation: '满足' },
        { emoji: '😚', word: 'kiss', translation: '亲吻' },
        { emoji: '😙', word: 'kissing', translation: '亲亲' },
        { emoji: '😭', word: 'cry', translation: '哭泣' },
        { emoji: '😢', word: 'sad', translation: '伤心' },
        { emoji: '😤', word: 'angry', translation: '生气' },
        { emoji: '😠', word: 'mad', translation: '恼怒' },
        { emoji: '🤬', word: 'rage', translation: '暴怒' },
        { emoji: '😱', word: 'scared', translation: '害怕' },
        { emoji: '😨', word: 'fearful', translation: '恐惧' },
        { emoji: '😰', word: 'anxious', translation: '焦虑' },
        { emoji: '😥', word: 'worried', translation: '担心' },
        { emoji: '😓', word: 'stressed', translation: '压力' },
        { emoji: '😩', word: 'tired', translation: '疲惫' },
        { emoji: '🥱', word: 'yawn', translation: '打哈欠' },
        { emoji: '😪', word: 'drowsy', translation: '困乏' },
        { emoji: '🤤', word: 'drool', translation: '垂涎' },
        { emoji: '😵', word: 'dizzy', translation: '晕眩' },
        { emoji: '🤐', word: 'silent', translation: '沉默' },
        { emoji: '🤫', word: 'quiet', translation: '安静' },
        { emoji: '🤥', word: 'lie', translation: '说谎' },
        { emoji: '😶', word: 'speechless', translation: '无语' },
        { emoji: '😐', word: 'neutral', translation: '中性' },
        { emoji: '😑', word: 'expressionless', translation: '面无表情' },
        { emoji: '🫤', word: 'confused', translation: '困惑' },
        { emoji: '🫡', word: 'salute', translation: '敬礼' }
    ],
    colors: {
        background: '#FCE4EC',
        text: '#880E4F',
        score: '#EC407A'
    },
    sounds: {
        match: 'emotion-match.mp3',
        levelUp: 'emotion-levelup.mp3',
        background: 'emotion-bg.mp3'
    },
    scoreMultiplier: 1.2,
    particleEffects: {
        color: '#F48FB1',
        size: 5,
        speed: 2.5
    }
};

export default emotionTheme;