const foodTheme = {
    name: '食物主题',
    emojiData: [
        { emoji: '🍕', word: 'pizza', translation: '披萨' },
        { emoji: '🍔', word: 'hamburger', translation: '汉堡' },
        { emoji: '🍟', word: 'french fries', translation: '薯条' },
        { emoji: '🌭', word: 'hot dog', translation: '热狗' },
        { emoji: '🥪', word: 'sandwich', translation: '三明治' },
        { emoji: '🌮', word: 'taco', translation: '墨西哥卷' },
        { emoji: '🌯', word: 'burrito', translation: '墨西哥卷饼' },
        { emoji: '🥙', word: 'stuffed flatbread', translation: '皮塔饼' },
        { emoji: '🧆', word: 'falafel', translation: '沙拉三明治' },
        { emoji: '🥚', word: 'egg', translation: '鸡蛋' },
        { emoji: '🍳', word: 'fried egg', translation: '煎蛋' },
        { emoji: '🥘', word: 'paella', translation: '西班牙海鲜饭' },
        { emoji: '🍲', word: 'pot of food', translation: '炖菜' },
        { emoji: '🥣', word: 'bowl with spoon', translation: '碗和勺' },
        { emoji: '🥗', word: 'green salad', translation: '蔬菜沙拉' },
        { emoji: '🍿', word: 'popcorn', translation: '爆米花' },
        { emoji: '🧈', word: 'butter', translation: '黄油' },
        { emoji: '🧀', word: 'cheese', translation: '奶酪' },
        { emoji: '🥓', word: 'bacon', translation: '培根' },
        { emoji: '🥩', word: 'steak', translation: '牛排' },
        { emoji: '🍖', word: 'meat on bone', translation: '肉' },
        { emoji: '🍗', word: 'chicken leg', translation: '鸡腿' },
        { emoji: '🥟', word: 'dumpling', translation: '饺子' },
        { emoji: '🥠', word: 'fortune cookie', translation: '幸运饼干' },
        { emoji: '🥡', word: 'takeout box', translation: '外卖盒' },
        { emoji: '🍱', word: 'bento box', translation: '便当' },
        { emoji: '🍚', word: 'cooked rice', translation: '米饭' },
        { emoji: '🍜', word: 'noodles', translation: '面条' },
        { emoji: '🍝', word: 'spaghetti', translation: '意大利面' },
        { emoji: '🍣', word: 'sushi', translation: '寿司' },
        { emoji: '🍤', word: 'fried shrimp', translation: '炸虾' },
        { emoji: '🍥', word: 'fish cake', translation: '鱼饼' },
        { emoji: '🥮', word: 'moon cake', translation: '月饼' },
        { emoji: '🍡', word: 'dango', translation: '团子' },
        { emoji: '🍧', word: 'shaved ice', translation: '刨冰' },
        { emoji: '🍨', word: 'ice cream', translation: '冰淇淋' },
        { emoji: '🍰', word: 'shortcake', translation: '蛋糕' },
        { emoji: '🧁', word: 'cupcake', translation: '纸杯蛋糕' },
        { emoji: '🥧', word: 'pie', translation: '派' },
        { emoji: '🍪', word: 'cookie', translation: '饼干' },
        { emoji: '🍫', word: 'chocolate bar', translation: '巧克力' },
        { emoji: '🍬', word: 'candy', translation: '糖果' },
        { emoji: '🍭', word: 'lollipop', translation: '棒棒糖' },
        { emoji: '🍮', word: 'custard', translation: '布丁' },
        { emoji: '🍯', word: 'honey pot', translation: '蜂蜜' },
        { emoji: '🍵', word: 'tea', translation: '茶' },
        { emoji: '☕', word: 'coffee', translation: '咖啡' },
        { emoji: '🧃', word: 'juice box', translation: '果汁' },
        { emoji: '🥤', word: 'soda', translation: '汽水' },
        { emoji: '🧋', word: 'bubble tea', translation: '珍珠奶茶' },
        { emoji: '🍶', word: 'sake', translation: '清酒' }
    ],
    colors: {
        background: '#FFF3E0',
        text: '#E65100',
        score: '#FB8C00'
    },
    sounds: {
        match: 'food-match.mp3',
        levelUp: 'food-levelup.mp3',
        background: 'food-bg.mp3'
    },
    scoreMultiplier: 1.2,
    particleEffects: {
        color: '#FFB74D',
        size: 5,
        speed: 2.5
    }
};

export default foodTheme;