const jobTheme = {
    name: '职业主题',
    emojiData: [
        { emoji: '👨‍⚕️', word: 'doctor', translation: '医生' },
        { emoji: '👩‍⚕️', word: 'nurse', translation: '护士' },
        { emoji: '👨‍🏫', word: 'teacher', translation: '老师' },
        { emoji: '👨‍🌾', word: 'farmer', translation: '农民' },
        { emoji: '👨‍🍳', word: 'chef', translation: '厨师' },
        { emoji: '👨‍🔧', word: 'mechanic', translation: '机械师' },
        { emoji: '👨‍🏭', word: 'factory worker', translation: '工厂工人' },
        { emoji: '👨‍💼', word: 'office worker', translation: '上班族' },
        { emoji: '👨‍🔬', word: 'scientist', translation: '科学家' },
        { emoji: '👨‍💻', word: 'programmer', translation: '程序员' },
        { emoji: '👨‍🎨', word: 'artist', translation: '艺术家' },
        { emoji: '👨‍✈️', word: 'pilot', translation: '飞行员' },
        { emoji: '👨‍🚀', word: 'astronaut', translation: '宇航员' },
        { emoji: '👮', word: 'police', translation: '警察' },
        { emoji: '🧑‍🚒', word: 'firefighter', translation: '消防员' },
        { emoji: '👷', word: 'construction worker', translation: '建筑工人' },
        { emoji: '🧑‍🏭', word: 'engineer', translation: '工程师' },
        { emoji: '🧑‍🌾', word: 'gardener', translation: '园丁' },
        { emoji: '🧑‍🍳', word: 'cook', translation: '厨师' },
        { emoji: '🧑‍🏫', word: 'professor', translation: '教授' },
        { emoji: '👨‍⚖️', word: 'judge', translation: '法官' },
        { emoji: '👨‍🎤', word: 'singer', translation: '歌手' },
        { emoji: '👨‍🎓', word: 'student', translation: '学生' },
        { emoji: '👨‍🦯', word: 'guide', translation: '导游' },
        { emoji: '👨‍🦼', word: 'therapist', translation: '治疗师' },
        { emoji: '👨‍🦽', word: 'caregiver', translation: '护理员' },
        { emoji: '💂', word: 'guard', translation: '保安' },
        { emoji: '🕵️', word: 'detective', translation: '侦探' },
        { emoji: '👨‍🎯', word: 'athlete', translation: '运动员' },
        { emoji: '👨‍📚', word: 'librarian', translation: '图书管理员' },
        { emoji: '👨‍💆', word: 'masseur', translation: '按摩师' },
        { emoji: '👨‍💇', word: 'barber', translation: '理发师' },
        { emoji: '👨‍🌺', word: 'florist', translation: '花匠' },
        { emoji: '👨‍🍞', word: 'baker', translation: '面包师' },
        { emoji: '👨‍📷', word: 'photographer', translation: '摄影师' },
        { emoji: '👨‍🎤', word: 'musician', translation: '音乐家' },
        { emoji: '👨‍🎨', word: 'painter', translation: '画家' },
        { emoji: '👨‍⚖️', word: 'lawyer', translation: '律师' },
        { emoji: '👨‍🏫', word: 'coach', translation: '教练' },
        { emoji: '👨‍🔧', word: 'electrician', translation: '电工' },
        { emoji: '👨‍🏭', word: 'carpenter', translation: '木匠' },
        { emoji: '👨‍🌾', word: 'fisherman', translation: '渔夫' },
        { emoji: '👨‍🍳', word: 'pastry chef', translation: '糕点师' },
        { emoji: '👨‍🎓', word: 'graduate', translation: '毕业生' },
        { emoji: '👨‍🏫', word: 'lecturer', translation: '讲师' },
        { emoji: '👨‍💻', word: 'developer', translation: '开发者' },
        { emoji: '👨‍🔬', word: 'researcher', translation: '研究员' },
        { emoji: '👨‍🎨', word: 'designer', translation: '设计师' },
        { emoji: '👨‍✈️', word: 'captain', translation: '船长' },
        { emoji: '👨‍🚀', word: 'cosmonaut', translation: '宇航员' },
        { emoji: '👮', word: 'sheriff', translation: '警长' }
    ],
    colors: {
        background: '#E3F2FD',
        text: '#0D47A1',
        score: '#1976D2'
    },
    sounds: {
        match: 'job-match.mp3',
        levelUp: 'job-levelup.mp3',
        background: 'job-bg.mp3'
    },
    scoreMultiplier: 1.2,
    particleEffects: {
        color: '#64B5F6',
        size: 5,
        speed: 2.5
    }
};

export default jobTheme;