const plantTheme = {
    name: '植物主题',
    emojiData: [
        { emoji: '🌸', word: 'cherry blossom', translation: '樱花' },
        { emoji: '🌹', word: 'rose', translation: '玫瑰' },
        { emoji: '🌺', word: 'hibiscus', translation: '芙蓉' },
        { emoji: '🌻', word: 'sunflower', translation: '向日葵' },
        { emoji: '🌼', word: 'blossom', translation: '花朵' },
        { emoji: '🌷', word: 'tulip', translation: '郁金香' },
        { emoji: '🌱', word: 'seedling', translation: '幼苗' },
        { emoji: '🌲', word: 'evergreen', translation: '常青树' },
        { emoji: '🌳', word: 'tree', translation: '树' },
        { emoji: '🌴', word: 'palm', translation: '棕榈树' },
        { emoji: '🌵', word: 'cactus', translation: '仙人掌' },
        { emoji: '🌾', word: 'sheaf', translation: '稻穗' },
        { emoji: '🌿', word: 'herb', translation: '草药' },
        { emoji: '☘️', word: 'shamrock', translation: '三叶草' },
        { emoji: '🍀', word: 'clover', translation: '四叶草' },
        { emoji: '🍁', word: 'maple', translation: '枫叶' },
        { emoji: '🍂', word: 'fallen leaf', translation: '落叶' },
        { emoji: '🍃', word: 'leaf', translation: '树叶' },
        { emoji: '🎋', word: 'bamboo', translation: '竹子' },
        { emoji: '🎍', word: 'pine', translation: '松树' },
        { emoji: '💐', word: 'bouquet', translation: '花束' },
        { emoji: '🥀', word: 'wilted flower', translation: '枯萎的花' },
        { emoji: '🌶️', word: 'chili', translation: '辣椒' },
        { emoji: '🌽', word: 'corn', translation: '玉米' },
        { emoji: '🥜', word: 'peanut', translation: '花生' },
        { emoji: '🍄', word: 'mushroom', translation: '蘑菇' },
        { emoji: '🪴', word: 'potted plant', translation: '盆栽' },
        { emoji: '🎄', word: 'christmas tree', translation: '圣诞树' },
        { emoji: '🪷', word: 'lotus', translation: '莲花' },
        { emoji: '🪸', word: 'coral', translation: '珊瑚' },
        { emoji: '🥕', word: 'carrot', translation: '胡萝卜' },
        { emoji: '🥬', word: 'leafy green', translation: '绿叶菜' },
        { emoji: '🥦', word: 'broccoli', translation: '西兰花' },
        { emoji: '🥒', word: 'cucumber', translation: '黄瓜' },
        { emoji: '🍅', word: 'tomato', translation: '番茄' },
        { emoji: '🍆', word: 'eggplant', translation: '茄子' },
        { emoji: '🥑', word: 'avocado', translation: '牛油果' },
        { emoji: '🍎', word: 'red apple', translation: '红苹果' },
        { emoji: '🍐', word: 'pear', translation: '梨' },
        { emoji: '🍊', word: 'tangerine', translation: '橘子' },
        { emoji: '🍋', word: 'lemon', translation: '柠檬' },
        { emoji: '🍌', word: 'banana', translation: '香蕉' },
        { emoji: '🍉', word: 'watermelon', translation: '西瓜' },
        { emoji: '🍇', word: 'grapes', translation: '葡萄' },
        { emoji: '🍓', word: 'strawberry', translation: '草莓' },
        { emoji: '🫐', word: 'blueberries', translation: '蓝莓' },
        { emoji: '🍒', word: 'cherries', translation: '樱桃' },
        { emoji: '🍑', word: 'peach', translation: '桃子' },
        { emoji: '🥝', word: 'kiwi', translation: '猕猴桃' },
        { emoji: '🍍', word: 'pineapple', translation: '菠萝' },
        { emoji: '🥥', word: 'coconut', translation: '椰子' }
    ],
    colors: {
        background: '#E8F5E9',
        text: '#1B5E20',
        score: '#43A047'
    },
    sounds: {
        match: 'plant-match.mp3',
        levelUp: 'plant-levelup.mp3',
        background: 'plant-bg.mp3'
    },
    scoreMultiplier: 1.2,
    particleEffects: {
        color: '#81C784',
        size: 5,
        speed: 2.5
    }
};

export default plantTheme;