const seasoningTheme = {
    name: '调味主题',
    emojiData: [
        { emoji: '🧂', word: 'salt', translation: '盐' },
        { emoji: '🌶️', word: 'chili pepper', translation: '辣椒' },
        { emoji: '🧄', word: 'garlic', translation: '大蒜' },
        { emoji: '🧅', word: 'onion', translation: '洋葱' },
        { emoji: '🌿', word: 'herb', translation: '香草' },
        { emoji: '🍯', word: 'honey', translation: '蜂蜜' },
        { emoji: '🫚', word: 'ginger', translation: '生姜' },
        { emoji: '🥄', word: 'spoon', translation: '勺子' },
        { emoji: '🧉', word: 'mate', translation: '马黛茶' },
        { emoji: '🫘', word: 'beans', translation: '豆子' },
        { emoji: '🥜', word: 'peanuts', translation: '花生' },
        { emoji: '🌰', word: 'chestnut', translation: '栗子' },
        { emoji: '🍶', word: 'sake', translation: '清酒' },
        { emoji: '🫖', word: 'teapot', translation: '茶壶' },
        { emoji: '🍵', word: 'tea', translation: '茶' },
        { emoji: '🧃', word: 'juice', translation: '果汁' },
        { emoji: '🥛', word: 'milk', translation: '牛奶' },
        { emoji: '🍼', word: 'bottle', translation: '奶瓶' },
        { emoji: '🫗', word: 'liquid', translation: '液体' },
        { emoji: '🧊', word: 'ice', translation: '冰块' },
        { emoji: '🍾', word: 'champagne', translation: '香槟' },
        { emoji: '🍷', word: 'wine', translation: '葡萄酒' },
        { emoji: '🍸', word: 'cocktail', translation: '鸡尾酒' },
        { emoji: '🍹', word: 'tropical drink', translation: '热带饮料' },
        { emoji: '🍺', word: 'beer', translation: '啤酒' },
        { emoji: '🍻', word: 'beer mugs', translation: '啤酒杯' },
        { emoji: '🥂', word: 'clinking glasses', translation: '碰杯' },
        { emoji: '🥃', word: 'tumbler glass', translation: '威士忌杯' },
        { emoji: '🫙', word: 'jar', translation: '罐子' },
        { emoji: '🥫', word: 'canned food', translation: '罐头食品' },
        { emoji: '🧂', word: 'seasoning', translation: '调味料' },
        { emoji: '🌶️', word: 'hot pepper', translation: '辣椒' },
        { emoji: '🧄', word: 'garlic clove', translation: '蒜瓣' },
        { emoji: '🧅', word: 'red onion', translation: '红洋葱' },
        { emoji: '🌿', word: 'fresh herbs', translation: '新鲜香草' },
        { emoji: '🍯', word: 'wild honey', translation: '野生蜂蜜' },
        { emoji: '🫚', word: 'fresh ginger', translation: '新鲜生姜' },
        { emoji: '🥄', word: 'measuring spoon', translation: '量勺' },
        { emoji: '🧉', word: 'herbal mate', translation: '草本马黛茶' },
        { emoji: '🫘', word: 'black beans', translation: '黑豆' },
        { emoji: '🥜', word: 'roasted peanuts', translation: '烤花生' },
        { emoji: '🌰', word: 'roasted chestnut', translation: '烤栗子' },
        { emoji: '🍶', word: 'rice wine', translation: '米酒' },
        { emoji: '🫖', word: 'ceramic teapot', translation: '陶瓷茶壶' },
        { emoji: '🍵', word: 'green tea', translation: '绿茶' },
        { emoji: '🧃', word: 'fruit juice', translation: '果汁' },
        { emoji: '🥛', word: 'fresh milk', translation: '鲜牛奶' },
        { emoji: '🍼', word: 'warm milk', translation: '温牛奶' },
        { emoji: '🫗', word: 'sauce pouring', translation: '倒酱料' },
        { emoji: '🧊', word: 'ice cube', translation: '冰块' }
    ],
    colors: {
        background: '#FFF3E0',
        text: '#E65100',
        score: '#FF9800'
    },
    sounds: {
        match: 'seasoning-match.mp3',
        levelUp: 'seasoning-levelup.mp3',
        background: 'seasoning-bg.mp3'
    },
    scoreMultiplier: 1.25,
    particleEffects: {
        color: '#FFE0B2',
        size: 4,
        speed: 2.3
    }
};

export default seasoningTheme;